### ISSUE TITLE
Crafting Recipes

### ISSUE THREAD

**Issue by DalekCraft2** [Z4OLLIEZ4/Space#1]
Crafting recipes for the Space items are not unlocked upon obtaining the necessary materials. The recipes will unlock only after creating the item, and, even then, will not always show up in the recipe book, despite the "Recipes unlocked" message displaying before.

Update: They will show up in the book, but will not show always show up in the "craftable" section, even if all of the materials are present. They also see space items as their base items (i.e. wires as redstone).

**Comment by Z4OLLIEZ4** [comment]
I'm not sure what you mean by the "craftable" section and recipes getting unlocked. There is no unlock system for recipes in space and they are all visible using the guide.

**Comment by DalekCraft2** [comment]
I refer to the recipe book.

**Comment by Z4OLLIEZ4** [comment]
Ah, I'll try to make a workaround for this.
Thank you for the quick reply.
