### ISSUE TITLE
I experience some lag with certains items during crafting

### ISSUE THREAD

**Issue by killiangcnperez** [Z4OLLIEZ4/Space#14]
Hi,

When player put items in the workbench it just cause some lag and decrease the tps to 10...
This issue is only for few items like carbon, iron dust etc. I try to disable recipe from the config and the bug still persist while the recipe do nothing.

Plus, I tried to disable then override the craft with another plugin using the same nbt and it doesn't work at all

Thanks again.

**Comment by Z4OLLIEZ4** [comment]
Please open a ticket on the discord server in future rather than using the wiki for support
Thank you :)
