### ISSUE TITLE
已按照WIKI照做，火箭没反应

### ISSUE THREAD

**Issue by Leoparking** [Z4OLLIEZ4/Space#16]
燃料已填充，右键坐上火箭，点击星球，但没有任何反应
![Y)3 R8QS9)%WDIUVYKF2~P3](https://github.com/Z4OLLIEZ4/Space/assets/141799770/5c7d5c85-9209-4f9a-8b2a-34409005ccd5)
![8I 9)B3FJJ5420MM LD7M58](https://github.com/Z4OLLIEZ4/Space/assets/141799770/1f412b90-c126-4e9c-9e83-b475f158d531)

**Comment by Z4OLLIEZ4** [comment]
You do not click on the planet to launch, but instead the "launch" button. You have incorrectly merged resource packs with another plugin so it is not displaying.

Please re-merge resource packs and your issue should resolve
