### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by Leoparking** [Z4OLLIEZ4/Space#17]
发射火箭到空中自己爆炸之后掉落回地面，什么事也没发生
![(@U%M(K$QWL~Y2P7C0$YY_3](https://github.com/Z4OLLIEZ4/Space/assets/141799770/8c603cef-bd1b-4f16-8640-c9f3ffa7c089)
并且尝试传送到自己的空间站时报错
服务器崩溃
![~S 0{I0}NS~ NU%GG(QE BT](https://github.com/Z4OLLIEZ4/Space/assets/141799770/5bd39255-5205-45a5-886a-78912faf84b5)
![G8%%7Z8F}{S~BKDG2~988WI](https://github.com/Z4OLLIEZ4/Space/assets/141799770/bee1f92b-1d4a-458c-a3ff-4b7d17bebc19)

**Comment by Z4OLLIEZ4** [comment]
Please open a ticket over on our discord server.

Have you followed the necessary setup instructions? It looks like you haven't generated the required worlds

**Comment by Leoparking** [comment]
> Please open a ticket over on our discord server.
> 
> Have you followed the necessary setup instructions? It looks like you haven't generated the required worlds

然而我的服务端不兼容MV世界插件，使用其他方式创建的太空无法被你的插件识别。希望作者能更新一下，把世界创建集成到太空插件里
However, my server is not compatible with the “MV” World plugin, and spaces created using other methods cannot be recognized by your Space plugin. I hope the author can update and integrate worlds creation into the Space plugin

**Comment by Leoparking** [comment]
<img width="538" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/9473995b-fcef-4f21-b473-4d202c233df3">
<img width="370" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/c5cde92d-99cc-4d2c-8980-2ea53d5831a8">


> Please open a ticket over on our discord server.
> 
> Have you followed the necessary setup instructions? It looks like you haven't generated the required worlds
