### ISSUE TITLE
Even if I directly reference the resource package that comes with the plugin, the launch interface cannot be displayed properly

### ISSUE THREAD

**Issue by Leoparking** [Z4OLLIEZ4/Space#19]
This has already been reflected before, and I thought it was an issue with my own resource pack
https://github.com/Z4OLLIEZ4/Space/issues/16

It should have been like this
![image](https://github.com/Z4OLLIEZ4/Space/assets/141799770/1eb9b6ad-5f91-4679-9bac-6ebe040c2648)

But in reality, it's like this
![UC`VTXSO9B9}%3}8A$~M@ 5](https://github.com/Z4OLLIEZ4/Space/assets/141799770/ce8c46ac-1303-4af1-a310-fed75fafe640)

But this time I'm using your resource pack directly, and it's useless
<img width="449" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/33041253-aa44-4f72-9b3b-60bfa1c1c92f">

**Comment by Leoparking** [comment]
A solution has been found on the client side: disable "force unicode fonts", but such fonts are also too unsightly
<img width="357" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/64ff615f-87fe-4f1a-a4c4-036967d5b938">

**Comment by Z4OLLIEZ4** [comment]
This issue has been resolved in latest.
