### ISSUE TITLE
Airtight Blocks

### ISSUE THREAD

**Issue by DalekCraft2** [Z4OLLIEZ4/Space#2]
Some blocks, like ladders and slabs, will cause suffocation whilst the player climbs or stands upon them respectively. I feel as if blocks like this should be treated as air blocks rather than as full blocks, because the plugin will think that the player is standing with their head inside a block, and think that they are suffocating.

Additionally, slabs should be airtight if they are part of the floor or ceiling of a structure, because they do not have holes in those positions.

**Comment by Z4OLLIEZ4** [comment]
These blocks can be added/removed from the list of non-airtight blocks in the config.yml
