### ISSUE TITLE
Insulated is not working on netherite armor

### ISSUE THREAD

**Issue by haotian188977** [Z4OLLIEZ4/Space#20]
all four armors have this Enchantments but the cold weather still effect and hurt

**Comment by Z4OLLIEZ4** [comment]
I am unable to replicate this issue.
If you're using a version post 1.20, please try a fresh set of armor, as the Spigot enchantment API had drastic changes during this update resulting in a rewrite, breaking some older items
if the issue persists, please open a ticket in the space discord
