### ISSUE TITLE
Why does the resourcepack not include modifications to the sky

### ISSUE THREAD

**Issue by Leoparking** [Z4OLLIEZ4/Space#21]
Is there a blue sky and white clouds on the moon? This is too strange, isn't it
![}7A JVZ7)@QJU)VZ NMX1WN](https://github.com/Z4OLLIEZ4/Space/assets/141799770/18944c48-b075-4845-a722-f3f758616c10)

**Comment by Z4OLLIEZ4** [comment]
The Minecraft skybox cannot be altered per-world unfortunately, it is just a limitation of vanilla Minecraft.
As such, clouds are also client-side.
