### ISSUE TITLE
Why cannot I customize planet icons

### ISSUE THREAD

**Issue by Leoparking** [Z4OLLIEZ4/Space#22]
When using your own URL image, converting the URL to base64 and writing to the configuration file will result in an error
Such as
`aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0xlb3BhcmtpbmcvcGxhbmV0cy9tYWluL2p1cGl0ZXIucG5n`
对应的
`https://raw.githubusercontent.com/Leoparking/planets/main/jupiter.png`

<img width="1067" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/4bfbcbf9-ffa7-4545-8b00-ff479a0264cf">

<img width="675" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/3ca1ebc1-c8b0-404f-91d9-4536d6266778">
没有发生错误
<img width="326" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/63a286b6-2b1f-4af4-b182-54476e9c3b81">
<img width="529" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/b86c0dc3-e8c0-4352-825e-08a13e511dbe">
Unable to click on the World Manager, even directly removed the icon

Only URLs on NAMEMC are useful, such as
`aHR0cHM6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTJhZjBkMWEwZDgwZDI3ZDgzODQxYTliMzg5MGNmZjUzZDlhMWQ3OTVmYmU5ZDBjZTgyMDBhNDljOGEzZGM1MQ==`
对应的
`https://textures.minecraft.net/texture/a2af0d1a0d80d27d83841a9b3890cff53d9a1d795fbe9d0ce8200a49c8a3dc51`
<img width="846" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/5d3e19c8-d66b-4a8a-8508-3fec6fb8d13d">
<img width="380" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/f2fded9d-5acb-4104-848d-b1276ff5d451">
<img width="940" alt="image" src="https://github.com/Z4OLLIEZ4/Space/assets/141799770/62a07175-eb05-4ae8-98e0-651ba28cfadc">

**Comment by Z4OLLIEZ4** [comment]
Minecraft uses it's own Base64 system for skulls, it is not just an encoded link. 
Using a website such as [minecraft-heads](https://minecraft-heads.com/) it's possible to link skulls by taking their "give code" in game, and using the Base64 provided there. For example:
To embed a "jupiter" icon from [this](https://minecraft-heads.com/custom-heads/head/568-jupiter) page, we'd need to find the "give" code in the "commands" section:

`/give @p minecraft:player_head{display:{Name:'{"text":"Jupiter"}'},SkullOwner:{Id:[I;-1818032849,1012220503,-1426985022,-1815857567],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjhhYWE4YTM1NjFlODBlZjFmOTU2MWYxNzIxMWU3NzBkZTE4YTlmOThjMjY5MWVjZjlkNjk2NTU5YTFiOTE4YyJ9fX0="}]}}} 1`

There we take the "Value tag", in this case: 
`eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjhhYWE4YTM1NjFlODBlZjFmOTU2MWYxNzIxMWU3NzBkZTE4YTlmOThjMjY5MWVjZjlkNjk2NTU5YTFiOTE4YyJ9fX0=`

This is the Base64 string expected in the worlds.yml, and will produce a skull output in game
