### ISSUE TITLE
The pickaxe instantly transforms into an antenna after synthesis

### ISSUE THREAD

**Issue by Leoparking** [Z4OLLIEZ4/Space#23]
Watching this video, when it is taken out, it immediately turns into an antenna

Uploading 镐变成天线.mp4…

**Comment by Z4OLLIEZ4** [comment]
Please open a ticket on discord. We are unable to see videos here and you'll get much quicker response times over there.

**Comment by Leoparking** [comment]
> 请在 discord 上开票。我们无法在这里看到视频，而您将在那里获得更快的响应时间。


The video has been added, please take a look
