### ISSUE TITLE
Oxygen collector, bubble generator, and oxygen refiller not working

### ISSUE THREAD

**Issue by DalekCraft2** [Z4OLLIEZ4/Space#3]
Note: I do have solar panels. Six of them.

The oxygen collector, even whilst surrounded by leaves and connected to six solar panels, will never have above 1/16000 energy. The bubble generator, whilst connected to six solar panels and to the oxygen collector, will have the oxygen values changing to 10, 7, 9, 6, and 8, in that order, on loop. The oxygen refiller, even whilst near the bubble generator and with a heavy oxygen tank in the inventory with it, will not refill the tank. I am also in an oxygen atmosphere, so it should be working without the generator anyway.

![image](https://user-images.githubusercontent.com/50336832/104777048-0ac76180-5749-11eb-9288-5c2a733a3ed9.png)
![image](https://user-images.githubusercontent.com/50336832/104777065-11ee6f80-5749-11eb-83e8-0c1798e65251.png)
![image](https://user-images.githubusercontent.com/50336832/104777077-19157d80-5749-11eb-81f3-661e6ebc7094.png)
![image](https://user-images.githubusercontent.com/50336832/104777117-27639980-5749-11eb-995e-f803ad8c981c.png)

**Comment by Z4OLLIEZ4** [comment]
Have you attempted to add more oxygen collectors or solar panels to your setup? Different machines use energy/oxygen at different rates

**Comment by DalekCraft2** [comment]
I forgot to mention that the oxygen level in the oxygen collector is at maximum, and the energy in the bubble generator is at maximum.

**Comment by DalekCraft2** [comment]
By the way, issues can be closed by mentioning updates to the code in GitHub, rather than closing them before updating.

**Comment by Z4OLLIEZ4** [comment]
Fixed in version 6.3
