### ISSUE TITLE
Suggestion: Make the gravity system use slow falling instead of levitation

### ISSUE THREAD

**Issue by DalekCraft2** [Z4OLLIEZ4/Space#4]
The gravity system currently uses small increments of levitation. However, this causes damage in mid-air to send players flying into the sky, and it makes elytras unusable. Slow falling could be used instead, and could also be given in increments (albeit, larger ones) as a substitute to make the gravity less buggy.

**Comment by Z4OLLIEZ4** [comment]
The reason levitation was in use for so long was to allow for support on pre 1.13 versions, although this support has now been dropped as space only supports versions of 1.14.x and above.
I'll add an option for use of slow falling as opposed to levitation.
Thank you for the suggestion.
